- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Actualizar los repositorios de apt
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include: tasks/paquetes.yml
    - include: tasks/anaconda.yml
    - include: tasks/practicas_rustup.yml
    - include: tasks/root_rustup.yml
    - include: tasks/administrador_rustup.yml
    


