- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Actualizar los repositorios de apt
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include: tasks/packages.yml

