---
- name: Correr la configuraci칩n b치sica tras una instalaci칩n de sistema operativo
  hosts: all
  become: true
  vars_files:
    - passwords.yml

  tasks:
    - name: Asegurar que el grupo practicas existe con id 1001 
      ansible.builtin.group:
        name: practicas
        state: present
        gid: 1001

    - name: A침adir usuario practicas
      ansible.builtin.user:
        name: practicas
        uid: 1001
        group: practicas
        update_password: on_create
        password: "{{ansible_practicas_password | password_hash('sha512')}}"
        
    - name: Fully upgrade the Ubuntu system
      apt:
        upgrade: full
        update_cache: yes
        
    - name: Add SSH public key to authorized_keys for the ansible user
      lineinfile:
        path: /home/ansible/.ssh/authorized_keys
        line: "{{ ansible_ssh_public_key }}"
        create: yes
        owner: ansible
        group: ansible
        mode: "0600"

    - name: Add SSH public key to authorized_keys for the practicas user
      lineinfile:
        path: /home/practicas/.ssh/authorized_keys
        line: "{{ ansible_ssh_public_key }}"
        create: yes
        owner: practicas
        group: practicas
        mode: "0600"

    - name: Install some packages
      apt:
        name: 
          - ansible
          - git
          - openssh-server
        state: present

