- hosts: all
  become: true
  
  pre_tasks:
    - name: Actualizar los repositorios de apt
      apt:
        update_cache: yes
        upgrade: full
      changed_when: false

  vars_files:
    - ../passwords.yml

  tasks:
    - include_tasks: ../tasks/change_passwords.yml
      vars:
        passwords: "{{ vars }}"

    #- include_tasks: tasks/anaconda.yml
    #- include_tasks: tasks/anaconda.yml
    #- include_tasks: tasks/practicas_rustup.yml
    #- include_tasks: tasks/root_rustup.yml
    #- include_tasks: tasks/administrador_rustup.yml
    #- include_tasks: tasks/paquetes_cargo.yml

    


