- name: Comprobar si cargo está instalado  para el usuario administrador
  become_user: "administrador"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  failed_when: false

- name: Descargar rust
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Instalar rust/cargo para el usuario admininstrador
  when: cargo_exists is failed
  become: true
  become_user: "administrador"
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
