- name: Comprobar si cargo está instalado 
  become_user: "administrador"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Descargar rust
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Instalar rust/cargo para el usuario practicas
  when: cargo_exists is failed
  become: true
  become_user: "administrador"
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
