- name: Actualizar usuario practicas
  ansible.builtin.user:
    name: practicas
    uid: 1001
    group: practicas
    update_password: always
    password: "{{ansible_practicas_password | password_hash('sha512')}}"
    state: present

- name: Actualizar usuario administrador
  ansible.builtin.user:
    name: administrador
    update_password: always
    password: "{{ansible_administrador_password | password_hash('sha512')}}"
    state: present

- name: Actualizar usuario ansible
  ansible.builtin.user:
    name: ansible
    update_password: always
    password: "{{ansible_ansible_user_password | password_hash('sha512')}}"
    state: present
