
- name: Añadir cron job para ansible-pull
  cron:
    user: ansible
    name: "Ansible Pull"
    minute: "0"
    hour: "*"
    job: "/usr/bin/ansible-pull -o -U https://github.com/mcasl/ansible_dimia.git local.yml"
