- name: Add ansible ppa repository
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible
    
- name: Instalar paquetes varios
  package:
    upgrade: full
    update_cache: yes
    name:
      - make
      - sshpass
      - pkg-config
      - libssl-dev
      - curl
      - htop
      - mc
      - tmux
      - wireguard
      - wakeonlan
      - virtualbox
      - parallel
      - net-tools
      - nmap
      - ghex
      - outguess
      - ansible
