- name: Instalar paquetes varios
  package:
    name:
      - make
      - pkg-config
      - libssl-dev
      - curl
      - htop
      - mc
      - tmux
      - wireguard
      - wakeonlan
      - virtualbox
      
      
