- name: Asegurar que el grupo ansible existe
  ansible.builtin.group:
    name: ansible
    system: true
    state: present
    
- name: Añadir usuario ansible
  ansible.builtin.user:
    name: ansible
    group: ansible
    system: true
    update_password: on_create
    password: "{{ansible_ansible_user_password | password_hash('sha512')}}"
    state: present
    
- name: sudoers | Create sudoers.d files
  copy:
    content: 'ansible ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/sudoer_ansible
    owner: root
    group: root
    mode: "0440" # Set proper permissions
    force: yes
    validate: /usr/sbin/visudo -csf %s

